### Copying 
a crutial in Deep learning sometime when you want to preserve some tensor or to use the same tensor for two different we create a 
 copy of that tensor 

We can create the copy of tensor by simple assignment operator but that doesnt help much.
as when using the assignment operator the variable points to the same memoery address where it was previously created. 

This cabe displayed as follows 

In [3]:
import torch
a =  torch.rand(2,2)
b = a 
print("memoery address of a an be given respectively ")
print(id(a))
id(b)


print("This means that if any change will be done to the a tensor that would be reflected on the b tensor as well")

a +=1

print(a)
print(b)

memoery address of a an be given respectively 
2462068982240
This means that if any change will be done to the a tensor that would be reflected on the b tensor as well
tensor([[1.8590, 1.5929],
        [1.1200, 1.4689]])
tensor([[1.8590, 1.5929],
        [1.1200, 1.4689]])


## To avoid this we can use the clone() to avoid this and create a separate memory of the the tensor at a differnt location in the memory 

In [5]:
c = a.clone()
print("Now the memory address of c would be different from a and b since we used the clone method")
print(id(c))
print(id(a))

Now the memory address of c would be different from a and b since we used the clone method
2461507295248
2462068982240


In [6]:
## Any change to the a will not affect the c tensor but will affect the b tensor since it is jus the reference of a

a+=1
print(a)
print(c)

tensor([[3.8590, 3.5929],
        [3.1200, 3.4689]])
tensor([[2.8590, 2.5929],
        [2.1200, 2.4689]])
